{% set name = "bip32" %}
{% set version = "3.4" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/darosior/python-bip32/archive/refs/tags/{{ version }}.tar.gz
  sha256: 82515eba9a891f1a18faeba7ae8d1d88589eeeaae4961f0f7fd3a0ceb0c2c503
  patches:
    - fix-coincurve-version.patch

build:
  noarch: python
  script: {{ PYTHON }} -m pip install . --use-pep517 -vvv
  number: 1

requirements:
  host:
    - base58 >=2.1.0
    - coincurve >=15.0.0,<20
    - pip
    - python {{ python_min }}
  run:
    - base58 >=2.1.0
    - coincurve >=15.0.0,<20
    - python >={{ python_min }}

test:
  imports:
    - bip32
  requires:
    - pip
    - pytest
    - python {{ python_min }}
  source_files:
    - tests/
  commands:
    - pip check
    - pytest -v tests

about:
  home: http://github.com/darosior/python-bip32
  summary: Minimalistic implementation of the BIP32 key derivation scheme
  license: MIT
  license_file: LICENCE

extra:
  recipe-maintainers:
    - MementoRC
